### ISSUE TITLE
Add 404 Not Found Page and Update Routing

### ISSUE THREAD

**Issue by kodeCraze** [Jaishree2310/GlassyUI-Components#7]
### Problem Statement
Currently, the GlassyUI application does not have a 404 Not Found page. When users navigate to a non-existent route, they do not receive a clear message indicating that the page does not exist.

### Proposed Solution
1. **Create a NotFoundPage Component:**
   - Design a 404 Not Found page using a glassmorphic design.
   - Ensure the page is responsive for mobile, iPad, and desktop devices.
   - Include a button on the page that navigates users back to the home page.

2. **Update App Component:**
   - Add a route for the NotFoundPage component.
   - Ensure that any unmatched routes redirect to the NotFoundPage.

### Expected Outcome
- Users will see a 404 Not Found page when they navigate to a non-existent route.
- The page will be visually appealing and consistent with the GlassyUI design.
- Users will have an easy way to navigate back to the home page.

### Additional Context
- This feature will improve user experience by providing clear feedback when users try to access non-existent pages.
- It aligns with standard web application practices of handling 404 errors gracefully.

**Comment by kodeCraze** [comment]
Hi @Jaishree2310,

I updated only 2 files in the code. On my local system, everything is working fine and there are no errors. However, when I upload the code to the GitHub dev branch, it shows a production error. Is there anything else I need to add or check?

**Comment by Jaishree2310** [comment]
@kodeCraze, Thank you for your valuable contribution to my project. Your efforts help drive its progress and are greatly appreciated. Your support means a lot to me and the project's success.
I hope you will continue to address other issues to further enhance the project. Additionally, there's a persistent 404 error whenever the components are not displayed correctly. I want this issue to be resolved so that all components are present and look consistent with the others.
